let ol1=document.createElement('ol');
let li1 = document.createElement('li');
li1.textContent = 'Andhra Pradesh';
let li2 = document.createElement('li');
li2.textContent = 'Arunachal Pradesh';
let li3 = document.createElement('li');
li3.textContent = 'Himachal Pradesh';
let li4 = document.createElement('li');
li4.textContent = 'Madhya Pradesh';
let li5 = document.createElement('li');
li5.textContent = 'Uttar Pradesh';
let li6 = document.createElement('li');
li6.textContent = 'Karnataka';
ol1.appendChild(li1);
ol1.appendChild(li2);
ol1.appendChild(li3);
ol1.appendChild(li4);
ol1.appendChild(li5);
ol1.appendChild(li6);
document.body.appendChild(ol1);
console.log(ol1);